[workspace]
resolver = "2"
members = [
    "protocol",
    "core",
    "gatewayd",
]

[workspace.package]
version = "1.1.2"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
thiserror = "1"
tracing = "0.1"
dashmap = "6"
uuid = { version = "1", features = ["v4"] }
