//! gatewayd/src/setup.rs
//!
//! Interactive setup wizard for users (Phase 6). `gatewayd --setup [file.yaml]`
//! walks through the WHOLE gateway config, asking one question at a time with
//! sensible defaults shown in [brackets]. Pressing Enter accepts the default.
//!
//! Design rules (agreed with the user):
//! - Everything in English (the gateway speaks English to its users).
//! - Defaults for every field — a user who just presses Enter gets a working
//!   config.
//! - Validation on input: a value that would break the gateway is re-asked,
//!   never silently accepted.
//! - Ends with a warning: "change values you do not understand only after
//!   reading the docs" — the wizard is for users, devs edit YAML directly.
//!
//! Output is generated by a small YAML string builder (not serde_yaml) so the
//! file is human-readable, commented, and matches config.example.yaml.

use std::io::{BufRead, Write};

/// Runs the wizard. `output` = file to write; defaults to `config.yaml`.
pub fn run(output: Option<String>) -> anyhow::Result<()> {
    let out_path = output.unwrap_or_else(|| "config.yaml".to_string());
    let stdin = std::io::stdin();
    let mut input = stdin.lock();

    println!("------------------------------------------------------------");
    println!(" gatewayd setup");
    println!(" Answer one question at a time. Press Enter to accept the");
    println!(" default shown in [brackets]. Type Ctrl-C to abort.");
    println!("------------------------------------------------------------");

    // --- Network -------------------------------------------------------
    println!("\n# Network");
    let listen = ask_str(&mut input, "TCP listen address", "0.0.0.0:8347");
    let http_listen = ask_str(&mut input, "HTTP listen address", "0.0.0.0:8348");
    let public_url = ask_str(
        &mut input,
        "Public URL (published in the agent card)",
        "http://localhost:8348",
    );

    // --- Security -------------------------------------------------------
    println!("\n# Security");
    let tokens = ask_tokens(&mut input);

    // --- Agents ---------------------------------------------------------
    println!("\n# Agents");
    let agent_count = ask_num(&mut input, "How many agents?", 1);
    let mut agents: Vec<AgentSpec> = Vec::new();
    for i in 0..agent_count {
        println!("\n  Agent #{}", i + 1);
        let name = ask_str(&mut input, "  Agent id (unique)", &format!("agent-{}", i + 1));
        let transport = ask_str(&mut input, "  Transport (stdio)", "stdio");
        let command_raw = ask_str(
            &mut input,
            "  Command (space separated, e.g. claurst acp)",
            "claurst acp",
        );
        let command: Vec<String> = command_raw
            .split_whitespace()
            .map(|s| s.to_string())
            .collect();
        let cwd = ask_optional(&mut input, "  Working directory (empty = inherit)");
        agents.push(AgentSpec {
            name,
            transport,
            command,
            cwd,
        });
    }

    // --- Tasks ----------------------------------------------------------
    println!("\n# Tasks");
    let task_store_dir = ask_str(&mut input, "Task store directory", "/tmp/gateway/tasks");
    let task_retention_days = ask_num(&mut input, "Task retention (days)", 7);
    let turn_lease_timeout_secs = ask_num(&mut input, "Turn lease timeout (seconds)", 30);
    let agent_call_timeout_secs = ask_num(&mut input, "Agent call timeout (seconds)", 120);

    // --- Logging ---------------------------------------------------------
    println!("\n# Logging");
    let log_level = ask_str(&mut input, "Log level (error/warn/info/debug/trace)", "info");
    let log_output = ask_str(&mut input, "Log output (stdout/file)", "stdout");
    let (log_path, log_max_file_mb, log_max_files, log_max_total_mb) = if log_output == "file" {
        let path = ask_str(&mut input, "Log file path", "/var/log/acp-a2a-gateway/gateway.log");
        let max_file = ask_num(&mut input, "Max file size (MB)", 100);
        let max_files = ask_num(&mut input, "Max file count", 10);
        let max_total = ask_num(&mut input, "Max total size (MB)", 1000);
        (path, max_file, max_files, max_total)
    } else {
        (
            String::new(),
            0,
            0,
            0,
        )
    };

    // --- Buffer (Phase 1): event log --------------------------------------
    println!("\n# Event buffer (durable stream buffer, source of truth for resubscribe)");
    let event_log_enabled = ask_bool(&mut input, "Enable durable event buffer?", true);
    let (event_log_path, event_log_max_mb) = if event_log_enabled {
        let path = ask_str(&mut input, "Event log database path", "/tmp/gateway/event_log.db");
        let max_mb = ask_num(&mut input, "Event log max size (MB)", 100);
        (path, max_mb)
    } else {
        (String::new(), 0)
    };

    // --- Task store backend (Phase 1) -------------------------------------
    println!("\n# Task store backend (sqlite replaces file storage)");
    let task_store_enabled = ask_bool(&mut input, "Enable sqlite task store?", true);
    let (task_store_path, task_store_max_mb) = if task_store_enabled {
        let path = ask_str(&mut input, "Task store database path", "/tmp/gateway/task_store.db");
        let max_mb = ask_num(&mut input, "Task store max size (MB)", 500);
        (path, max_mb)
    } else {
        (String::new(), 0)
    };

    // --- Journal (Phase 5) -------------------------------------------------
    println!("\n# Journal (durable event log for health alerts, disconnects, approvals)");
    let journal_enabled = ask_bool(&mut input, "Enable journal?", true);
    let (journal_path, journal_max_mb, journal_retention_days) = if journal_enabled {
        let path = ask_str(&mut input, "Journal database path", "/tmp/gateway/journal.db");
        let max_mb = ask_num(&mut input, "Journal max size (MB)", 100);
        let days = ask_num(&mut input, "Journal retention (days, 0 = keep everything)", 30);
        (path, max_mb, days)
    } else {
        (String::new(), 0, 0)
    };

    // --- Health monitor (Phase 5) -------------------------------------------
    println!("\n# Health monitor (periodic DB size + stream usage check)");
    let health_enabled = ask_bool(&mut input, "Enable health monitor?", true);
    let (health_interval, health_warn_pct) = if health_enabled {
        let interval = ask_num(&mut input, "Check interval (seconds)", 300);
        let warn_pct = ask_num(&mut input, "DB size warning at % of limit", 80);
        (interval, warn_pct)
    } else {
        (0, 0)
    };

    // --- Approvals (Phase 7) ------------------------------------------------
    println!("\n# Approvals (human gate for new agents via `gatewayd --approve <name>`)");
    let approvals_enabled = ask_bool(&mut input, "Enable agent approvals?", true);
    let approvals_path = if approvals_enabled {
        ask_str(
            &mut input,
            "Approvals database path",
            "/tmp/gateway/approvals.db",
        )
    } else {
        String::new()
    };

    // --- Render --------------------------------------------------------------
    let yaml = render(
        &listen,
        &http_listen,
        &public_url,
        &tokens,
        &agents,
        &task_store_dir,
        task_retention_days,
        turn_lease_timeout_secs,
        agent_call_timeout_secs,
        &log_level,
        &log_output,
        &log_path,
        log_max_file_mb,
        log_max_files,
        log_max_total_mb,
        event_log_enabled,
        &event_log_path,
        event_log_max_mb,
        task_store_enabled,
        &task_store_path,
        task_store_max_mb,
        journal_enabled,
        &journal_path,
        journal_max_mb,
        journal_retention_days,
        health_enabled,
        health_interval,
        health_warn_pct,
        approvals_enabled,
        &approvals_path,
    );

    std::fs::write(&out_path, &yaml)
        .map_err(|e| anyhow::anyhow!("failed to write config: {e}"))?;

    println!("\n------------------------------------------------------------");
    println!(" Config written to {}", out_path);
    println!();
    println!(" IMPORTANT");
    println!("  Change values you do not understand ONLY after reading the");
    println!("  gateway docs. A wrong token, port or database path will");
    println!("  prevent the gateway from starting.");
    println!("  Developers: edit the YAML directly instead of re-running");
    println!("  this wizard.");
    println!("------------------------------------------------------------");
    Ok(())
}

struct AgentSpec {
    name: String,
    transport: String,
    command: Vec<String>,
    cwd: String,
}

// --- prompt helpers ---------------------------------------------------------

fn prompt(input: &mut impl BufRead, label: &str, default: &str) -> String {
    print!("{} [{}]: ", label, default);
    std::io::stdout().flush().ok();
    let mut line = String::new();
    if input.read_line(&mut line).ok().filter(|n| *n > 0).is_none() {
        eprintln!("aborted (no input)");
        std::process::exit(1);
    }
    let v = line.trim().to_string();
    if v.is_empty() {
        return default.to_string();
    }
    v
}

fn ask_str(input: &mut impl BufRead, label: &str, default: &str) -> String {
    loop {
        let v = prompt(input, label, default);
        if !v.trim().is_empty() {
            return v.trim().to_string();
        }
        eprintln!("  value must not be empty");
    }
}

/// Optional string: Enter = empty (the value is not written to the config).
fn ask_optional(input: &mut impl BufRead, label: &str) -> String {
    prompt(input, label, "").trim().to_string()
}

fn ask_num(input: &mut impl BufRead, label: &str, default: u64) -> u64 {
    loop {
        let v = prompt(input, label, &default.to_string());
        match v.trim().parse::<u64>() {
            Ok(n) => return n,
            Err(_) => eprintln!("  expected a whole number"),
        }
    }
}

fn ask_bool(input: &mut impl BufRead, label: &str, default: bool) -> bool {
    loop {
        let d = if default { "yes" } else { "no" };
        let v = prompt(input, label, d).to_lowercase();
        match v.as_str() {
            "yes" | "y" | "true" => return true,
            "no" | "n" | "false" => return false,
            _ => eprintln!("  expected yes or no"),
        }
    }
}

fn ask_tokens(input: &mut impl BufRead) -> Vec<String> {
    loop {
        let v = prompt(input, "Auth tokens (comma separated, at least one)", "t-dev-local-001");
        let tokens: Vec<String> = v
            .split(',')
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();
        if tokens.is_empty() {
            eprintln!("  at least one token is required");
            continue;
        }
        return tokens;
    }
}

// --- YAML rendering -----------------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn render(
    listen: &str,
    http_listen: &str,
    public_url: &str,
    tokens: &[String],
    agents: &[AgentSpec],
    task_store_dir: &str,
    task_retention_days: u64,
    turn_lease_timeout_secs: u64,
    agent_call_timeout_secs: u64,
    log_level: &str,
    log_output: &str,
    log_path: &str,
    log_max_file_mb: u64,
    log_max_files: u64,
    log_max_total_mb: u64,
    event_log_enabled: bool,
    event_log_path: &str,
    event_log_max_mb: u64,
    task_store_enabled: bool,
    task_store_path: &str,
    task_store_max_mb: u64,
    journal_enabled: bool,
    journal_path: &str,
    journal_max_mb: u64,
    journal_retention_days: u64,
    health_enabled: bool,
    health_interval: u64,
    health_warn_pct: u64,
    approvals_enabled: bool,
    approvals_path: &str,
) -> String {
    let mut s = String::new();
    s.push_str("# gatewayd config (generated by `gatewayd --setup`).\n");
    s.push_str(&format!("listen: \"{listen}\"\n"));
    s.push_str(&format!("http_listen: \"{http_listen}\"\n"));
    s.push_str(&format!("public_url: \"{public_url}\"\n\n"));

    s.push_str("tokens:\n");
    for t in tokens {
        s.push_str(&format!("  - \"{t}\"\n"));
    }

    s.push_str("\nagents:\n");
    for a in agents {
        s.push_str(&format!("  {}:\n", a.name));
        s.push_str(&format!("    transport: {}\n", a.transport));
        let cmd = a
            .command
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect::<Vec<_>>()
            .join(", ");
        s.push_str(&format!("    command: [{cmd}]\n"));
        if !a.cwd.is_empty() {
            s.push_str(&format!("    cwd: \"{}\"\n", a.cwd));
        }
    }

    s.push_str(&format!("\ntask_store_dir: \"{task_store_dir}\"\n"));
    s.push_str(&format!("task_retention_days: {task_retention_days}\n"));
    s.push_str(&format!("turn_lease_timeout_secs: {turn_lease_timeout_secs}\n"));
    s.push_str(&format!("agent_call_timeout_secs: {agent_call_timeout_secs}\n"));

    s.push_str("\nlogging:\n");
    s.push_str(&format!("  level: {log_level}\n"));
    s.push_str(&format!("  output: {log_output}\n"));
    if log_output == "file" {
        s.push_str("  file:\n");
        s.push_str(&format!("    path: \"{log_path}\"\n"));
        s.push_str(&format!("    max_file_size_mb: {log_max_file_mb}\n"));
        s.push_str(&format!("    max_files: {log_max_files}\n"));
        s.push_str(&format!("    max_total_size_mb: {log_max_total_mb}\n"));
    }

    s.push_str("\n# Durable event buffer (source of truth for tasks/resubscribe).\n");
    s.push_str("event_log:\n");
    s.push_str(&format!("  enabled: {}\n", bool_yaml(event_log_enabled)));
    if event_log_enabled {
        s.push_str("  storage_backend: sqlite\n");
        s.push_str(&format!("  storage_path: \"{event_log_path}\"\n"));
        s.push_str(&format!("  max_size_mb: {event_log_max_mb}\n"));
    }

    s.push_str("\n# Task store backend (sqlite replaces the file storage).\n");
    s.push_str("task_store:\n");
    s.push_str(&format!("  enabled: {}\n", bool_yaml(task_store_enabled)));
    if task_store_enabled {
        s.push_str("  storage_backend: sqlite\n");
        s.push_str(&format!("  storage_path: \"{task_store_path}\"\n"));
        s.push_str(&format!("  max_size_mb: {task_store_max_mb}\n"));
    }

    s.push_str("\n# Journal: durable log for health alerts, disconnects, approvals.\n");
    s.push_str("journal:\n");
    s.push_str(&format!("  enabled: {}\n", bool_yaml(journal_enabled)));
    if journal_enabled {
        s.push_str("  storage_backend: sqlite\n");
        s.push_str(&format!("  storage_path: \"{journal_path}\"\n"));
        s.push_str(&format!("  max_size_mb: {journal_max_mb}\n"));
        s.push_str(&format!("  retention_days: {journal_retention_days}\n"));
    }

    s.push_str("\n# Health monitor: periodic DB size + stream usage check.\n");
    s.push_str("health:\n");
    s.push_str(&format!("  enabled: {}\n", bool_yaml(health_enabled)));
    if health_enabled {
        s.push_str(&format!("  check_interval_secs: {health_interval}\n"));
        s.push_str(&format!("  db_size_warn_pct: {health_warn_pct}\n"));
    }

    s.push_str("\n# Approvals: human gate for new agents via `gatewayd --approve <name>`.\n");
    s.push_str("approvals:\n");
    s.push_str(&format!("  enabled: {}\n", bool_yaml(approvals_enabled)));
    if approvals_enabled {
        s.push_str(&format!("  storage_path: \"{approvals_path}\"\n"));
    }

    s
}

fn bool_yaml(b: bool) -> &'static str {
    if b {
        "true"
    } else {
        "false"
    }
}